with Version.Hash.Tests;
with Version.Repository.Tests;
with Version.Repository_Format.Tests;
with Version.Sha256_Interop_Tests;
with Version.Filesystem_Guard.Tests;
with Version.Refs.Tests;
with Version.Reftable.Tests;
with Version.Objects.Tests;
with Version.Status.Tests;
with Version.Write.Tests;
with Version.Restore.Tests;
with Version.Reset.Tests;
with Version.Move.Tests;
with Version.Clean.Tests;
with Version.Bundle.Tests;
with Version.Apply.Tests;
with Version.Format_Patch.Tests;
with Version.Am.Tests;
with Version.Cherry.Tests;
with Version.Range_Diff.Tests;
with Version.Shortlog.Tests;
with Version.Grep.Tests;
with Version.Describe.Tests;
with Version.Notes.Tests;
with Version.Blame.Tests;
with Version.Branch.Tests;
with Version.Remove.Tests;
with Version.History.Tests;
with Version.Tags.Tests;
with Version.Remotes.Tests;
with Version.Fetch.Tests;
with Version.Clone.Tests;
with Version.Push.Tests;
with Version.Lock.Tests;
with Version.Merge_State.Tests;
with Version.Merge.Tests;
with Version.Config.Tests;
with Version.Init.Tests;
with Version.Reflog.Tests;
with Version.Pkt_Line.Tests;
with Version.Transport.Http.Tests;
with Version.Transport.Ssh.Tests;
with Version.Upload_Pack.Tests;
with Version.Receive_Pack.Tests;
with Version.Pack_Write.Tests;
with Version.Packed_Refs.Tests;
with Version.Ref_Transaction.Tests;
with Version.Checkout.Tests;
with Version.Tracking.Tests;
with Version.Ignore.Tests;
with Version.Diff.Tests;
with Version.Log.Tests;
with Version.Show.Tests;
with Version.Revisions.Tests;
with Version.Maintenance.Tests;
with Version.Security.Tests;
with Version.Platform.Tests;
with Version.Windows_Portability.Tests;
with Version.Release.Tests;
with Version.Rebase.Tests;
with Version.Ref_Format.Tests;
with Version.Text_Filter.Tests;
with Version.Cherry_Pick.Tests;
with Version.Revert.Tests;
with Version.Stash.Tests;
with Version.Pathspec.Tests;
with Version.Shallow.Tests;
with Version.Sparse.Tests;
with Version.Worktrees.Tests;
with Version.Submodules.Tests;
with Version.Archive.Tests;
with Version.Git_Compat.Tests;
with Version.Command_Corruption.Tests;
with Version.Cross_Feature.Tests;

package body Version_Suite is

   function Suite return AUnit.Test_Suites.Access_Test_Suite is
      Result : constant AUnit.Test_Suites.Access_Test_Suite :=
        new AUnit.Test_Suites.Test_Suite;
   begin
      pragma Warnings (Off, "use of an anonymous access type allocator");
      Result.Add_Test (new Version.Hash.Tests.Test_Case);
      Result.Add_Test (new Version.Repository.Tests.Test_Case);
      Result.Add_Test (new Version.Repository_Format.Tests.Test_Case);
      Result.Add_Test (new Version.Sha256_Interop_Tests.Test_Case);
      Result.Add_Test (new Version.Filesystem_Guard.Tests.Test_Case);
      Result.Add_Test (new Version.Refs.Tests.Test_Case);
      Result.Add_Test (new Version.Reftable.Tests.Test_Case);
      Result.Add_Test (new Version.Objects.Tests.Test_Case);
      Result.Add_Test (new Version.Status.Tests.Test_Case);
      Result.Add_Test (new Version.Write.Tests.Test_Case);
      Result.Add_Test (new Version.Restore.Tests.Test_Case);
      Result.Add_Test (new Version.Reset.Tests.Test_Case);
      Result.Add_Test (new Version.Move.Tests.Test_Case);
      Result.Add_Test (new Version.Clean.Tests.Test_Case);
      Result.Add_Test (new Version.Bundle.Tests.Test_Case);
      Result.Add_Test (new Version.Apply.Tests.Test_Case);
      Result.Add_Test (new Version.Format_Patch.Tests.Test_Case);
      Result.Add_Test (new Version.Am.Tests.Test_Case);
      Result.Add_Test (new Version.Cherry.Tests.Test_Case);
      Result.Add_Test (new Version.Range_Diff.Tests.Test_Case);
      Result.Add_Test (new Version.Shortlog.Tests.Test_Case);
      Result.Add_Test (new Version.Grep.Tests.Test_Case);
      Result.Add_Test (new Version.Describe.Tests.Test_Case);
      Result.Add_Test (new Version.Notes.Tests.Test_Case);
      Result.Add_Test (new Version.Blame.Tests.Test_Case);

      Result.Add_Test (new Version.Branch.Tests.Test_Case);
      Result.Add_Test (new Version.Remove.Tests.Test_Case);
      Result.Add_Test (new Version.History.Tests.Test_Case);
      Result.Add_Test (new Version.Tags.Tests.Test_Case);
      Result.Add_Test (new Version.Remotes.Tests.Test_Case);

      Result.Add_Test (new Version.Fetch.Tests.Test_Case);

      Result.Add_Test (new Version.Clone.Tests.Test_Case);
      Result.Add_Test (new Version.Push.Tests.Test_Case);
      Result.Add_Test (new Version.Lock.Tests.Test_Case);
      Result.Add_Test (new Version.Merge_State.Tests.Test_Case);
      Result.Add_Test (new Version.Merge.Tests.Test_Case);
      Result.Add_Test (new Version.Config.Tests.Test_Case);
      Result.Add_Test (new Version.Init.Tests.Test_Case);
      Result.Add_Test (new Version.Reflog.Tests.Test_Case);
      Result.Add_Test (new Version.Pkt_Line.Tests.Test_Case);
      Result.Add_Test (new Version.Transport.Http.Tests.Test_Case);
      Result.Add_Test (new Version.Transport.Ssh.Tests.Test_Case);

      Result.Add_Test (new Version.Upload_Pack.Tests.Test_Case);
      Result.Add_Test (new Version.Receive_Pack.Tests.Test_Case);
      Result.Add_Test (new Version.Pack_Write.Tests.Test_Case);
      Result.Add_Test (new Version.Packed_Refs.Tests.Test_Case);
      Result.Add_Test (new Version.Ref_Transaction.Tests.Test_Case);
      Result.Add_Test (new Version.Checkout.Tests.Test_Case);
      Result.Add_Test (new Version.Tracking.Tests.Test_Case);
      Result.Add_Test (new Version.Ignore.Tests.Test_Case);
      Result.Add_Test (new Version.Diff.Tests.Test_Case);
      Result.Add_Test (new Version.Log.Tests.Test_Case);
      Result.Add_Test (new Version.Show.Tests.Test_Case);

      Result.Add_Test (new Version.Revisions.Tests.Test_Case);
      Result.Add_Test (new Version.Maintenance.Tests.Test_Case);
      Result.Add_Test (new Version.Security.Tests.Test_Case);
      Result.Add_Test (new Version.Platform.Tests.Test_Case);
      Result.Add_Test (new Version.Windows_Portability.Tests.Test_Case);
      Result.Add_Test (new Version.Release.Tests.Test_Case);
      Result.Add_Test (new Version.Rebase.Tests.Test_Case);
      Result.Add_Test (new Version.Ref_Format.Tests.Test_Case);
      Result.Add_Test (new Version.Text_Filter.Tests.Test_Case);
      Result.Add_Test (new Version.Cherry_Pick.Tests.Test_Case);
      Result.Add_Test (new Version.Revert.Tests.Test_Case);
      Result.Add_Test (new Version.Stash.Tests.Test_Case);

      Result.Add_Test (new Version.Pathspec.Tests.Test_Case);
      Result.Add_Test (new Version.Shallow.Tests.Test_Case);
      Result.Add_Test (new Version.Sparse.Tests.Test_Case);
      Result.Add_Test (new Version.Worktrees.Tests.Test_Case);
      Result.Add_Test (new Version.Submodules.Tests.Test_Case);
      Result.Add_Test (new Version.Archive.Tests.Test_Case);
      Result.Add_Test (new Version.Git_Compat.Tests.Test_Case);
      Result.Add_Test (new Version.Command_Corruption.Tests.Test_Case);
      Result.Add_Test (new Version.Cross_Feature.Tests.Test_Case);
      pragma Warnings (On, "use of an anonymous access type allocator");
      return Result;
   end Suite;

end Version_Suite;